import { Component, OnInit } from '@angular/core';
import { CommonModule } from '@angular/common';
import { FormsModule } from '@angular/forms';
import { Router } from '@angular/router';
import { AuthService } from '../auth';
import { QuizService } from '../services/quiz.service';
import { Quiz } from '../interfaces/quiz.interface';

@Component({
  selector: 'app-add-quiz',
  standalone: true,
  imports: [CommonModule, FormsModule],
  templateUrl: './add-quiz.html',
  styleUrl: './add-quiz.css'
})
export class AddQuizComponent implements OnInit {
  newQuiz: Quiz = {
    id: null, // ID will be generated by the backend
    question: '',
    optA: '',
    optB: '',
    optC: '',
    optD: '',
    answer: ''
  };

  constructor(
    private authService: AuthService,
    private quizService: QuizService,
    private router: Router
  ) { }

  ngOnInit(): void {
    if (!this.authService.isLoggedIn() || !this.authService.isAdmin()) {
      this.router.navigate(['/login']);
      return;
    }
  }

  addQuiz(): void {
    this.quizService.addQuiz(this.newQuiz).subscribe({
      next: () => {
        alert('Quiz question added successfully!');
        this.router.navigate(['/quiz-list']);
      },
      error: (error: any) => {
        console.error('Error adding quiz question:', error);
        alert('Error adding quiz question: ' + (error.error || error.message));
      }
    });
  }

  goBack(): void {
    this.router.navigate(['/quiz-list']);
  }
}
